name: GBv

on: push

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          python-version: "3.7"
      - run: pip install selenium
      - run: python main.py
